quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:app}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:app}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://db:5432/app}
quarkus.datasource.devservices.enabled=false

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.host=0.0.0.0